export const ADD_TO_FAV = 'ADD_TO_FAV'
export const REMOVE_FROM_FAV = 'REMOVE_FROM_FAV'
export const LOADING = 'LOADING'
export const RESULTS_UPDATED = 'RESULTS_UPDATED'
export const FETCH_ERROR = 'FETCH_ERROR'
